function[]=push_KPCMX()
% %% update the trading system
make_copy('期货近月开平仓门限\*KPCTHK.txt','\\Acerpc\实时监控\jy')
make_copy('期货远月开平仓门限\*KPCTHK.txt','\\Acerpc\实时监控\yy')
make_copy('产品推送开平仓门限\BQ2ICLong_KPCMX.txt','\\Acerpc\实时监控\plot')
make_copy('产品推送开平仓门限\BQ2ICHedge_KPCMX.txt','\\Acerpc\实时监控\plot')
make_copy('产品推送开平仓门限\HJ1ICLongTest_KPCMX.txt','\\Acerpc\实时监控\plot')

% make_copy('现货择时开平仓门限\IC_XHZS.txt','\\Zhoufz-pc\ic\')
% make_copy('现货择时开平仓门限\IC_XHZS.txt','\\BAIQUAN-PC\ic\')
% make_copy('现货择时开平仓门限\IC_XHZS.txt','\\Huijin2\ic\')
% make_copy('现货择时开平仓门限\IC_XHZS.txt','\\Trading4\ic\')
% make_copy('现货择时开平仓门限\IC_XHZS.txt','\\Baiquan2trd1\ic\')
% make_copy('现货择时开平仓门限\IC_XHZS.txt','\\Xincheng1\ic\')
% make_copy('期货近月开平仓门限\IC_KPCTHK.txt','\\Zfz-pc\ic\')
% make_copy('期货近月开平仓门限\IC_KPCTHK.txt','\\Trading5\ic\')
% make_copy('期货近月开平仓门限\IC_KPCTHK.txt','\\Baiquan2trd2\ic\')

make_copy('产品推送开平仓门限\BQ1ICHedge_KPCMX.txt','\\Zfz-pc\ic\ ')
make_copy('产品推送开平仓门限\BQ1ICLong_KPCMX.txt','\\Zhoufz-pc\ic')
make_copy('产品推送开平仓门限\JQ1ICLong_KPCMX.txt','\\BAIQUAN-PC\ic\')
make_copy('产品推送开平仓门限\HJ1ICLong_KPCMX.txt','\\Huijin2\ic\')
make_copy('产品推送开平仓门限\GD2ICLong_KPCMX.txt','\\Trading4\ic\')
make_copy('产品推送开平仓门限\GD2ICHedge_KPCMX.txt','\\Trading5\ic\')
make_copy('产品推送开平仓门限\BQ2ICLong_KPCMX.txt','\\Baiquan2trd1\ic\')
make_copy('产品推送开平仓门限\BQ2ICHedge_KPCMX.txt','\\Baiquan2trd2\ic\')
make_copy('产品推送开平仓门限\HJ1ICLongTest_KPCMX.txt','\\Huijin1\ic\')
make_copy('产品推送开平仓门限\XD9ICLong_KPCMX.txt','\\Xincheng1\ic\')
% 
make_copy('产品推送开平仓门限\HJ1ICLongTest_KPCMX.txt','\\Zhouhu\ic\')
make_copy('产品推送开平仓门限\HJ1ICHedgeTest_KPCMX.txt','\\Zhouhu\ic\')

% make_copy('现货择时开平仓门限\IC_XHZS.txt','\\Zhouhu\ts仿真\kpcthk(N档)_zeshi\IC\')
% make_copy('期货近月开平仓门限\*KPCTHK.txt','\\Zhouhu\ts仿真\kpcthk(N档)_alpha\IC\')
